# Configuración de Kitty para Sway
# background #000000

# Opacidad
background_opacity 0.95
background_blur 20

hide_window_decorations yes

font_family monospace
# Tamaño de la Fuente
font_size 12.5

# Margen de destello interno
window_padding_width 10

enable_audio_bell no

# Cursor vertical
cursor_shape beam
# Velocidad de parpadeo del Cursor
cursor_blink_interval 0.5

map ctrl+shift+f5 load_config_file


# BEGIN_KITTY_THEME
# Tokyo Night Storm
include current-theme.conf
# END_KITTY_THEME
